# fly.toml app configuration file generated for beabot on 2024-03-13T16:31:36-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beabot'
primary_region = 'sjc'


[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
